---@diagnostic disable-next-line: undefined-global
local vim = vim

vim.keymap.set("n", "&", "1")
vim.keymap.set("n", "é", "2")
vim.keymap.set("n", '"', "3")
vim.keymap.set("n", "'", "4")
vim.keymap.set("n", "(", "5")
vim.keymap.set("n", "-", "6")
vim.keymap.set("n", "è", "7")
vim.keymap.set("n", "_", "8")
vim.keymap.set("n", "ç", "9")
vim.keymap.set("n", "à", "0")

vim.keymap.set("v", "&", "1")
vim.keymap.set("v", "é", "2")
vim.keymap.set("v", '"', "3")
vim.keymap.set("v", "'", "4")
vim.keymap.set("v", "(", "5")
vim.keymap.set("v", "-", "6")
vim.keymap.set("v", "è", "7")
vim.keymap.set("v", "_", "8")
vim.keymap.set("v", "ç", "9")
vim.keymap.set("v", "à", "0")

vim.keymap.set("n", "1", "&")
vim.keymap.set("n", "2", "é")
vim.keymap.set("n", "3", '"')
vim.keymap.set("n", "4", "'")
vim.keymap.set("n", "5", "(")
vim.keymap.set("n", "6", "-")
vim.keymap.set("n", "7", "è")
vim.keymap.set("n", "8", "_")
vim.keymap.set("n", "9", "ç")
vim.keymap.set("n", "0", "à")

vim.keymap.set("v", "1", "&")
vim.keymap.set("v", "2", "é")
vim.keymap.set("v", "3", '"')
vim.keymap.set("v", "4", "'")
vim.keymap.set("v", "5", "(")
vim.keymap.set("v", "6", "-")
vim.keymap.set("v", "7", "è")
vim.keymap.set("v", "8", "_")
vim.keymap.set("v", "9", "ç")
vim.keymap.set("v", "0", "à")
